default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: task_everyleaf_development
test:
  <<: *default
  database: task_everyleaf_test
production:
  <<: *default
  database: task_everyleaf_production
  username: task_everyleaf
  password: <%= ENV['TASK_EVERYLEAF_DATABASE_PASSWORD'] %>
